# ===================================================================
# Spring Boot configuration - Prod
# ===================================================================

spring:
    jackson:
        serialization.indent_output: true
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://192.168.100.209:1433;database=SGD;
        name: SGD
        username: sa
        password: "Agro2025!"
    acceso-datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://192.168.100.209:1433;database=SGD;
        name: SGD
        username: sa
        password: "Agro2025!"
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        database: SQL_SERVER
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
      
#serfor:
 # seguridad:
  #  ldap: 10.6.0.10
